startCaptureColor: "§c"
endCaptureColor: "§c"

infoCommandMessage1: "§6Название - "
infoCommandMessage2: "Владелец - "
infoCommandMessage3: "Захватчик - "

giveRewardMessage: "§6Ты получил свою награду!"
notGiveRewardMessage: "§6У тебя недостаточно монет или пытаешься взять слишком много!"
infoRewardMessage: "§6На твоём счету - "
reward: "rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAXTUlO
RU1JTkVOT01JX0JFTExZUE9VQ0g="